### ISSUE TITLE
Netlifyを設定してデプロイできるようにする

### ISSUE THREAD

**Issue by springaki** [shinosakarb/tebukuro#201]

**Comment by murajun1978** [comment]
docs: https://www.netlify.com/docs/

**Comment by murajun1978** [comment]
Successfully deployed 🚀 
https://baliff-hamster-76303.netlify.com

**Comment by murajun1978** [comment]
### TODO
- [ ] Add deploy preview
- [ ] Add notification for GitHub
- [ ] Add slack notification

docs: https://www.netlify.com/docs/continuous-deployment/#deploy-contexts

**Comment by murajun1978** [comment]
<img width="785" alt="add_template_for_netlify_by_murajun1978_ _pull_request__7_ _shinosakarb_tebukuro-client" src="https://user-images.githubusercontent.com/911903/31326311-e811eb74-ad00-11e7-8da8-03f61a6f2ec8.png">

↑ Do you need comment notifying results? 🤔

**Comment by murajun1978** [comment]
GitHub notifications only once.

**Comment by murajun1978** [comment]
Let's do that for now 💨
