### ISSUE TITLE
イベントを作成する

### ISSUE THREAD

**Issue by springaki** [shinosakarb/tebukuro#203]
- イベント作成できればOK
- (今は)誰でも作れる
- イベント名と説明文くらい

--- 

### やらないこと

- 参加者リストはここでは実装しない

## Todos
- [x] Event Show Pageの作成
- [x] Event Containerの作成
- [x] Event Componentの作成
- [x] Event New Pageの作成
- [x] EventForm Containerの作成
- [x] EventForm Componentの作成
- [x] Create Event Actionの作成
- [x] Fetch Event Actionの作成
- [x] Event Reducerの作成
- [x] Api接続モジュール（ApiClient）の作成 ( @murajun1978 )
- [x] Reduxと、Event New PageおよびEvent Show Pageの接続

**Comment by ytorii** [comment]
PRを出す順番は↓のような感じでしょうか？
現時点で着手して良ければ、PR出していきたいです。

- テスト用のパッケージ、設定ファイルの追加
- Event Componentの作成
- Event Containerの作成
- Api接続モジュール（ApiClient）の作成
- Event Actionの作成
- Event Reducerの作成
- Event Form Componentの作成
- Event Form Containerの作成
- EventList Componentの作成
- EventList Containerの作成
- Events Pageの作成

簡単なComponentの作成から入って、PR・CI・レビュー・マージのサイクルを回し始めたいと考えています。

**Comment by murajun1978** [comment]
@ytorii UIから作るのであれば
Page -> Container -> Componentの順番に作った方が動作確認もしやすいと思いますよー

**Comment by murajun1978** [comment]
@springaki このissueをEpicにしてもOK?

**Comment by ytorii** [comment]
ありがとうございます！ではその順番で作成していきます。

**Comment by springaki** [comment]
@murajun1978 Epicにするのは構わないですよ。規模や機能確認のタイミングがよくわからなかったので、Issueから作っていたのでした。

とはいえ、これが Epicになるの？ @ytorii さんが上げてくれている箇条書きがそのまま Issueの一個づつに対応するような感じですか？それならチェックボックス対応でも良さそうな気がしてるんですが、どうなんでしょう？

とはいえPRの単位は意味のある単位で最小にしておきたいとは思ってます。
まぁ一回やりやすいようにやってみてもらってもいいかなと思う 😊

**Comment by murajun1978** [comment]
@springaki @ytorii DescriptionにTodosを追加しました。

API clientは僕が実装したいなー (希望 ☺️

**Comment by murajun1978** [comment]
並び順も変えてみました。（開発がやりやすそうな順番で
EventListはやらない事になっていたので追加していません。

**Comment by ytorii** [comment]
順番の改善、ありがとうございます！
では、API client は宜しくお願いしますｗ
（実はエラーレスポンス時の処理とか、相談させて頂くつもりでした）

EventListを作らない場合、page の構造は以下の認識で合っていますか？
- index.js (トップページ)には Event 作成のフォームだけがある
- event.js（イベントページ）で name と description を表示する
- index には現時点では、各event へのリンクは貼らない

**Comment by springaki** [comment]
> タスクをissueにしるのはやり過ぎですかね😱
> チェックボックスにしますー

どうなんですかね 😄  開発速度とか内包する手数とかを鑑みつつ、みんながやりやすいような粒度を模索すればいいと思いますよー。基本的にはこれくらいの粒度が進めやすい印象をもっていますが、プロダクトとかチームによっても変わってくるので、色々議論できると嬉しいです。

**Comment by chimame** [comment]
バックエンド側でしないといけないこと

- [ ] communityがなくてもEventを作れるように変更する
- [ ] createのルーティングを変更 ( `/communities/:community_id/events` を `/events` に変更)
- [ ] Eventのvalidateを削除

**Comment by ytorii** [comment]
作業が全て完了したため、closeします！
