### ISSUE TITLE
DNS適用したい

### ISSUE THREAD

**Issue by springaki** [shinosakarb/tebukuro#217]
Frontend: http://tebukuro.shinosakarb.org
Backend: `tebukuro-api.shinosakarb.org`

### Todos
- [x] Setting DNS for Frontend
- [x] Setting DNS for Backend
- [x] Fix API URL of Frontend
- [x] TLS (Frontend)
- [ ] ~~TLS (Backend)~~

**Comment by ytorii** [comment]
フロントエンド側で接続先API のベースURL を変更する [PR](https://github.com/shinosakarb/tebukuro-client/pull/29)を作成しました。
最終的な URL が決まったら、PR を修正して対応します。

**Comment by murajun1978** [comment]
DNSの準備はOIK

**Comment by murajun1978** [comment]
client: http://tebukuro.shinosakarb.org/

**Comment by murajun1978** [comment]
### Todos
- [ ] Setting DNS fro backend
- [ ] TLS (backend, frontend)

**Comment by murajun1978** [comment]
Frontend TLS ready :smile:

**Comment by murajun1978** [comment]
Use CLOUD DNS :thinking:

**Comment by murajun1978** [comment]
Backend: http://tebukuro-api.shinosakarb.org:3000

**Comment by ytorii** [comment]
以下の対応を採るので、本件 close します。
- ドメイン名のサービスはメンバー全員が設定できるよう、Google Clound DNS を使用
- バックエンドのhttps 化については、 #283 で扱う
