### ISSUE TITLE
community作る

### ISSUE THREAD

**Issue by tono0123** [shinosakarb/tebukuro#6]
Userがcommunityを作るための機能を実装
### TODO
- [x] community model を作成
- [x] community controller を作成
- [x] community の spec を作成

**Comment by tono0123** [comment]
migrateしますね〜

**Comment by yukihirop** [comment]
- [x] community controllerを作成
をやります。

**Comment by murajun1978** [comment]
merged #37
